INSERT INTO BERTRAMWEISS.THEMA (ID, LETZTEAENDERUNG, "NAME") VALUES (0, 1388286215, 'Startseite');
INSERT INTO BERTRAMWEISS.VERSION (ID, AUTHOR, TEXT, VERSION) VALUES (0, 'System', 'Keine Version vorhanden.', 0);
INSERT INTO BERTRAMWEISS.THEMA_VERSION (THEMA_ID, CONTENTSET_ID) VALUES (0, 0);