CREATE TABLE THEMA (ID INTEGER DEFAULT GENERATED_BY_DEFAULT  NOT NULL GENERATED ALWAYS AS IDENTITY, LETZTEAENDERUNG BIGINT, "NAME" VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE VERSION (ID INTEGER DEFAULT GENERATED_BY_DEFAULT  NOT NULL GENERATED ALWAYS AS IDENTITY, AUTHOR VARCHAR(255), TEXT VARCHAR(10000), VERSION INTEGER, PRIMARY KEY (ID));
CREATE TABLE THEMA_VERSION (THEMA_ID INTEGER NOT NULL, CONTENTSET_ID INTEGER NOT NULL, PRIMARY KEY (THEMA_ID, CONTENTSET_ID));
INSERT INTO BERTRAMWEISS.THEMA (ID, LETZTEAENDERUNG, "NAME") VALUES (0, 1388286215, 'Startseite');
INSERT INTO BERTRAMWEISS.VERSION (ID, AUTHOR, TEXT, VERSION) VALUES (0, 'System', 'Keine Version vorhanden.', 0);
INSERT INTO BERTRAMWEISS.THEMA_VERSION (THEMA_ID, CONTENTSET_ID) VALUES (0, 0);